sources:
  - name: northwind 
    description: Data from Northwind ERP
    database: fea25_05
    schema: erp_northwind
    tables:
      - name: orders
        description: '{{ doc("orders_docs") }}'
        freshness: 
          warn_after:
            count: 5000
            period: day
          error_after:
            count: 20000
            period: day
        loaded_at_field: cast(order_date as timestamp)
        columns:
          - name: order_id
            description: Unique ID for this table
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - relationships:
                  field: customer_id
                  to: ref('stg_customers')
      - name: customers
        description: This table lists the customers from ERP Northwind
        columns:
          - name: customer_id
            description: Unique ID for this table
      - name: order_details
      - name: products
      - name: categories
      - name: suppliers
