sources:
  - name: northwind 
    database: fea25_05
    schema: raw_northwind
    tables:
      - name: orders
      - name: customers
      - name: order_details
      - name: products
      - name: category
      - name: suppliers
